Repository bislara/code-n-stitch, pull requests merged in 2020-10, with the labels that each got.

#48 Implemented a Paint App in Python using PyQt5
  .gitignore
  Paint Application/README.md
  Paint Application/main.py
  Paint Application/screenshot.png
Labels: ready for review

#45 Email Id extractor
  email_id_extractor/README.md
  email_id_extractor/email_id_extractor.py
  email_id_extractor/screenshot.png
  email_id_extractor/setup.py
Labels: ready for review

#44 Added Typing Speed Tester
  Typing_Speed_Test/README.md
  Typing_Speed_Test/typing_speed_test.py
Labels: ready for review

#47 Screen Recorder
  Screen Recorder/README.md
  Screen Recorder/Recording.avi
  Screen Recorder/capture.svg
  Screen Recorder/captureIT.py
  Screen Recorder/captureIT_img.jpg
  Screen Recorder/pause.svg
  Screen Recorder/record.png
  Screen Recorder/screenshot.jpg
  Screen Recorder/stop.svg
Labels: ready for review

#58 GitHub User Details
  Github_User_Details/README.md
  Github_User_Details/functions.py
  Github_User_Details/github.png
  Github_User_Details/gui.py
  Github_User_Details/main.py
  Github_User_Details/requirements.txt
  Github_User_Details/screenshot_cli.png
  Github_User_Details/screenshot_gui.png
  Github_User_Details/search.png
Labels: ready for review

#56 Added Wifi Password Getter Hack
  wifi_hack/README.md
  wifi_hack/images/gui_output.PNG
  wifi_hack/images/script.PNG
  wifi_hack/images/wifi.png
  wifi_hack/wifi_password_getter.py
  wifi_hack/wifi_password_getter_gui.py
Labels: ready for review

#69 added the issue labeller
  .github/issues_labeler.yml
  .github/workflows/issues_labeler.yml
Labels: ready for review

#82 Feature/OTP generator
  OTP/README.md
  OTP/otp.py
  OTP/otp_2_clipboard.jpeg
  OTP/requirements.txt
Labels: hacktoberfest-accepted

#95 Scrap all email from the website link in python
  Scrap_Email/README.md
  Scrap_Email/output.png
  Scrap_Email/requirements.txt
  Scrap_Email/scrap_email.py
Labels: hacktoberfest-accepted, ready for review

#104 75 ipl score notifier
  ipl_score_notifier/README.md
  ipl_score_notifier/ipl_score_notifier.py
  ipl_score_notifier/ipl_score_notifier2.py
  ipl_score_notifier/test.png
Labels: requested-change

#108 torrent searcher
  torrent_seacher/README.md
  torrent_seacher/main.py
  torrent_seacher/requirements.txt
Labels: hacktoberfest-accepted

#109 Video player
  video_player/README.md
  video_player/player.py
Labels: hacktoberfest-accepted

#54 added invisible cloak folder
  Invisible Cloak/README.md
  Invisible Cloak/Screenshot.png
  Invisible Cloak/invisible.py
  Invisible Cloak/requirements.txt
Labels: ready for review

#133 Adding auto assign in reviewers and assignes
  .github/auto_assign.yml
  .github/workflows/auto_assign_pr.yml
Labels: hacktoberfest-accepted

#161 CLI Based Encode and Decode Tool
  Python/Encode_Decode_Tool/README.md
  Python/Encode_Decode_Tool/Screenshots/Screenshot_1.png
  Python/Encode_Decode_Tool/Screenshots/Screenshot_2.png
  Python/Encode_Decode_Tool/Screenshots/Screenshot_3.png
  Python/Encode_Decode_Tool/Screenshots/Screenshot_4.png
  Python/Encode_Decode_Tool/Screenshots/Screenshot_5.png
  Python/Encode_Decode_Tool/enc.py
  Python/Encode_Decode_Tool/requirements.txt
Labels: hacktoberfest-accepted, requested-change
